# Generated by Django 5.0.6 on 2024-07-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('iddepago', models.AutoField(primary_key=True, serialize=False)),
                ('idperson', models.IntegerField()),
                ('pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
            ],
        ),
    ]
